// rAthena msg_athena.conf
// Message Configuration of char-server
// -----------------------
0: 初学者
1: 剑士
2: 魔法师
3: 弓箭手
4: 服事
5: 商人
6: 盗贼
7: 骑士
8: 牧师
9: 巫师
10: 铁匠
11: 猎人
12: 刺客
13: 十字军
14: 武僧
15: 贤者
16: 流氓
17: 炼金术士
18: 吟游诗人
19: 舞娘
20: 婚礼
21: 超级初学者
22: 神枪手
23: 忍者
24: 圣诞
25: 高级初学者
26: 高级剑士
27: 高级魔法师
28: 高级弓箭手
29: 高级服事
30: 高级商人
31: 高级盗贼
32: 领主骑士
33: 高阶牧师
34: 高阶巫师
35: 神工匠
//35: Mastersmith //IRO name
36: 神射手
37: 十字刺客
38: 圣殿十字军
39: 武术宗师
40: 博士
//40: Scholar //IRO name
41: 神行太保
42: 创造者
//42: Biochemist //IRO Name
43: 小丑
//43: Minstrel //IRO Name
44: 冠军舞者
45: 小初学者
46: 小剑士
47: 小魔法师
48: 小弓箭手
49: 小服事
50: 小商人
51: 小盗贼
52: 小骑士
53: 小牧师
54: 小巫师
55: 小铁匠
56: 小猎人
57: 小刺客
58: 小十字军
59: 小武僧
60: 小贤者
61: 小流氓
62: 小炼金术士
63: 小吟游诗人
64: 小舞娘
65: 超级小初学者
66: 跆拳
67: 星帝
68: 灵媒师
//79: FREE
//70: FREE
71: 夏日
72: 强尸
73: 死亡骑士
74: 黑暗收集者
75: 符文骑士
76: 咒术士
77: 游侠
78: 大主教
79: 机械工匠
80: 斩首者
81: 皇家卫士
82: 妖术师
83: 吟游诗人
//83: Maestro //IRO Name
84: 漫游者
85: 修罗
86: 基因学者
//86: Geneticist //IRO Name
87: 影狼
88: 小符文骑士
89: 小咒术士
90: 小游侠
91: 小大主教
92: 小机械工匠
93: 小斩首者
94: 小皇家卫士
95: 小妖术师
96: 小吟游诗人
97: 小漫游者
98: 小修罗
99: 小基因学者
100: 小影狼
101: Expanded Super Novice
102: Expanded Super Baby
103: Kagerou
104: Oboro
105: Hanbok
106: Rebellion
107: Oktoberfest
108: Summoner
109: Baby Summoner
110: 小忍者
111: 小影狼
112: 小胧
113: 小跆拳
114: 小星帝
115: 小灵媒师
116: 小神枪手
117: 小叛乱者
118: 星帝
119: 灵魂收割者
120: 小星帝
121: 小灵魂收割者
122: 龙骑士
123: 机匠
124: 影十字
125: 大法师
126: 红衣主教
127: 风鹰
128: 帝国卫士
129: 生化学者
130: 深渊追迹者
131: 元素大师
132: 审判者
133: 吟游诗人
134: 歌姬
135: 天帝
136: 灵魂行者
137: 真辉
138: 不知火
139: 夜巡者
140: 超级初学者
141: 灵魂使者

199: 未知职业

//Auction
200: 拍卖管理员
201: 拍卖
202: 谢谢，你赢得了拍卖！
203: 你的拍卖款项！
204: 没有找到你的拍卖买家。
205: 拍卖已取消。
206: 拍卖已结束。
207: 拍卖获胜者。
208: 有人出价高于你。
209: 你已出价更高。
210: 你赢得了拍卖。
211: 你的拍卖款项！

// @accountinfo
212: 没有找到符合条件“%s”的结果
213: 发生错误，请联系管理员。
214: 查询返回 %d 个结果，请提供更具体的条件……
215: [AID: %d] %s | %s | 等级：%d/%d | %s
216: 没有找到 ID 为“%d”的账号。
217: -- 账号 %d --
218: 用户：%s | GM 组：%d | 状态：%d
//219: FREE
//220: FREE
221: 账号邮箱：%s | 出生日期：%s
222: 上次 IP：%s（%s）
223: 此用户已登录 %d 次，上次登录时间为 %s
224: -- 角色详情 --
225: [槽位/CID：%d/%d] %s | %s | 等级：%d/%d | %s
226: 此账号没有角色。

// Achievements
227: GM
228: 成就奖励邮件
229: [%s] 成就奖励。
