// rAthena msg_athena.conf
// Message Configuration of login-server
// -----------------------
0: 未注册的 ID。
1: 密码错误。
2: 账号已过期。
3: 被服务器拒绝。
4: 被 GM 封锁。
5: 不是最新的游戏 EXE。
6: 已被封禁。
7: 服务器人数过多。
8: 公司账号限制
9: 被 DBA 封禁
10: 邮箱尚未确认
11: 被 GM 封禁
12: 正在处理数据库
13: 自我锁定
14: 不允许的群组
15: 不允许的群组
16: 账号不存在。
17: 登录信息仍然保留。
18: 正在调查黑客行为。
19: 正在调查错误。
20: 正在删除角色。
21: 正在删除配偶角色。
22: 未知错误。
